[tool.poetry]
name = "pyspace"
version = "0.1.0"
description = "Orbit analysis with Python"
authors = ["Antoine Barré <antoine.barre@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
